# Generated by Django 3.2.24 on 2024-03-26 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import lp_server.helpers
import publisher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('1', 'ONE-TIME'), ('2', 'MONTHLY')], default='2', help_text='The type of plan, e.g. one-time or monthly', max_length=2)),
                ('unique_id', models.CharField(help_text='The unique id by which the campaign can be identified by the partner', max_length=64, validators=[lp_server.helpers.validate_unique_id_strict])),
                ('name', publisher.models.BleachCharField(help_text='The name of the campaign', max_length=255)),
                ('impression_per_period', models.IntegerField(default=0, help_text='the number of impressions to be served during the period')),
                ('initial_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), help_text='initial start date of the campaign')),
                ('start_date', models.DateTimeField(help_text='start date of the campaign (changes each month for monthly plans)')),
                ('end_date', models.DateTimeField(blank=True, help_text='end date of the campaign', null=True)),
                ('target_url', publisher.models.BleachCharField(blank=True, max_length=1024, null=True, validators=[lp_server.helpers.validate_url], verbose_name='target url')),
                ('has_website', models.BooleanField(default=True, help_text='Whether or not the campaign creator needs a new website for the campaign')),
                ('source', publisher.models.BleachCharField(blank=True, max_length=32, null=True, verbose_name='campaign source')),
                ('medium', publisher.models.BleachCharField(blank=True, max_length=32, null=True, verbose_name='campaign medium')),
                ('approved', models.BooleanField(default=False, help_text='if the campaign is approved by the admin')),
                ('enabled', models.BooleanField(default=True, help_text='if the campaign is enabled by the creator and on going')),
                ('draft', models.BooleanField(default=False, help_text='if the campaign is to be saved as a draft by the creator')),
                ('removed', models.BooleanField(default=False, help_text='whether or not the organization admins have removed the campaign. Removed campaigns will not be displayed to users')),
                ('internal', models.BooleanField(default=False, help_text='whether or not the campaign is for an ASL19 project')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='accounts.organization')),
                ('target_regions', models.ManyToManyField(blank=True, to='preference.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('desired', models.BigIntegerField()),
                ('actual', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='publisher.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignFundingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='the amount of funding added to the campaign', max_digits=6)),
                ('payment_date', models.DateTimeField(help_text='the date the payment has gone through')),
                ('payment_confirmation', models.CharField(blank=True, help_text='Confirmation string received from the payment system', max_length=1024)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign funding history',
            },
        ),
        migrations.CreateModel(
            name='CampaignConsumptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text='The unique id by which the bill can be identified from the partner', max_length=32)),
                ('consumption_date', models.DateTimeField(help_text='the day which the consumption corresponds to')),
                ('number_of_impression', models.IntegerField(default=0, help_text='how many times the campaign has been presented to the user')),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, help_text='the amount of funding that has been consumed for the day the campaign', max_digits=6)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign consumption history',
            },
        ),
        migrations.AddConstraint(
            model_name='impression',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='unique_impression_yield'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('organization', 'unique_id'), name='unique_organization_id'),
        ),
    ]
