# Generated by Django 3.2.24 on 2024-03-26 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsHistoryAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, 'BEEPASS VPN'), (2, 'BEEPASS VPN X')], db_index=True, default=1)),
                ('status', models.CharField(choices=[('1', 'ACCEPTED'), ('2', 'INVALID')], default='2', max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hourly_requests', to='publisher.campaign')),
            ],
            options={
                'verbose_name_plural': 'Requests History Aggregate',
            },
        ),
        migrations.CreateModel(
            name='RequestsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'ACCEPTED'), ('2', 'INVALID')], db_index=True, default='2', max_length=2)),
                ('source', models.IntegerField(choices=[(1, 'BEEPASS VPN'), (2, 'BEEPASS VPN X')], db_index=True, default=1)),
                ('ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_address_fwd', models.CharField(blank=True, max_length=256, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='created')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=1000)),
                ('headers', models.JSONField(default=dict)),
                ('path', models.CharField(max_length=1000)),
                ('uri', models.CharField(max_length=2000)),
                ('host', models.CharField(max_length=1000)),
                ('meta', models.TextField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('is_secure', models.BooleanField()),
                ('is_ajax', models.BooleanField()),
                ('failure_cause', models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Requested servers not found or off'), ('2', 'CHECK_FOR_SERVERS Setting is set to False'), ('3', 'No Campaigns found')], default='0', max_length=2)),
                ('ownclient', models.BooleanField(default=True)),
                ('ownserver', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='publisher.campaign')),
            ],
            options={
                'verbose_name_plural': 'Requests History',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.outlineserver')),
            ],
        ),
        migrations.AddConstraint(
            model_name='requestshistoryaggregate',
            constraint=models.UniqueConstraint(fields=('status', 'campaign', 'timestamp', 'source'), name='unique_aggregate'),
        ),
    ]
