# Generated by Django 3.2.24 on 2024-03-26 20:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fa', max_length=2, verbose_name='Language')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About Paskoocheh')),
                ('contact_email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Contact Email')),
                ('privacy_policy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('terms_of_service', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Terms of Service')),
            ],
            options={
                'verbose_name_plural': 'Web Texts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=256)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('timezone', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'unique_together': {('country', 'city')},
            },
        ),
    ]
