version: '3'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: ./manage.py runserver 0.0.0.0:8001
        ports:
            - "8001:8001"
        volumes:
            - ./lp_server:/usr/src/app
            - ./private/prometheus/shared:/var/lib/prometheus   
        depends_on:
            - db
        networks:
            - backend
        env_file:
            - ./.env
        environment:
            - DEBUG=1
            - BUILD_ENV=local
            - DATABASE_HOST=db
            - 'SECRET_KEY=SeCrEtKeY'
            - DATABASE_USER=lpserver
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=lpserver
            - DATABASE_PORT=5432
            - CELERY_BROKER_URL=redis://:redis-pass@redis:6379
            - CELERY_RESULT_BACKEND=redis://:redis-pass@redis:6379
            - PROMETHEUS_MULTIPROC_DIR=/var/lib/prometheus

    db:
        image: postgres:11
        ports:
            - '5432:5432'
        volumes:
            - ./private/postgres-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            - POSTGRES_USER=lpserver
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=lpserver

    db-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: alias@mail.com
            PGADMIN_DEFAULT_PASSWORD: alias
        volumes:
            - ./private/pgadmin:/var/lib/pgadmin
        depends_on:
            - db
        ports:
            - '8080:80'
        networks:
            - backend

    redis:
        image: redis
        command: redis-server --requirepass redis-pass
        ports:
            - "6379:6379"
        networks:
            - backend

    celery:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        command: celery -A lp_server worker -l info
        volumes:
            - ./lp_server:/usr/src/app
        depends_on:
            - redis
        networks:
            - backend
        env_file:
            - ./.env
        environment:
            - DEBUG=1
            - BUILD_ENV=local
            - DATABASE_HOST=db
            - 'SECRET_KEY=SeCrEtKeY'
            - DATABASE_USER=lpserver
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=lpserver
            - DATABASE_PORT=5432
            - CELERY_BROKER_URL=redis://:redis-pass@redis:6379
            - CELERY_RESULT_BACKEND=redis://:redis-pass@redis:6379

    prometheus:
        image: prom/prometheus:latest
        volumes:
                - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - 9090:9090
        networks:
            - backend
networks:
    backend:
        driver: bridge
