# Generated by Django 3.2.24 on 2024-03-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('user_src', models.CharField(choices=[('TG', 'Telegram'), ('EM', 'Email'), ('SG', 'Signal'), ('NA', 'Unknows')], default='NA', max_length=2)),
                ('reputation', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_distributing', models.BooleanField(default=True)),
                ('dist_model', models.IntegerField(choices=[(0, 'Basic'), (1, 'Location Based'), (2, 'Fixed IP')], default=0, verbose_name='Distribution Model')),
                ('api_url', models.TextField(blank=True, null=True)),
                ('api_cert', models.TextField(blank=True, null=True)),
                ('prometheus_port', models.IntegerField(default=900)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('legacy', 'Legacy'), ('central', 'Central'), ('gtf', 'GTF')], default='legacy', max_length=64)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.location')),
                ('region', models.ManyToManyField(blank=True, to='preference.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
